trigger:
  branches:
    include:
      - main # Or the branch you want to trigger the pipeline on
    exclude:
      - stage2
# pr:
#   branches:
#     include:
#       - pr1
 
      

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, World!
  displayName: 'Print Hello, World!'
