trigger:
  - main
  - stage2

pr:
  branches:
    include:
    - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildBranch: $(Build.SourceBranchName)
  sourceBranch: $(System.PullRequest.SourceBranchName)

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building on branch $(buildBranch)"
    
    # Include main.yml for 'main' branch
    - ${{ if eq(variables['buildBranch'], 'main') }}:
      - template: main.yml

    # Include dev.yml for 'dev' branch
    - ${{ if eq(variables['buildBranch'], 'dev') }}:
      - template: dev.yml
    

# trigger:
#   branches:
#     include:
#       - main # Or the branch you want to trigger the pipeline on
#     exclude:
#       - stage2
# # pr:
# #   branches:
# #     include:
# #       - pr1
 
      

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: echo Hello, World!
#   displayName: 'Print Hello, World!'
