trigger: none  # Disable CI triggers for all branches

pr:
  branches:
    include:
      - main  # Trigger on PRs targeting the main branch
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, World!
  displayName: 'Print Hello, World!'
