resources:
  repositories:
    - repository: forPR
      
      name: harsha5401/forPR
      endpoint: github.com_harsha5401

trigger: none  # Disable CI triggers for all branches

pr:
  branches:
    include:
      - main  # Trigger on PRs targeting the main branch
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, World!
  displayName: 'Print Hello, World!'
