name: CI

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the pipeline on after merge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Azure DevOps Pipeline
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/hbasireddy/github
        pipeline-name: harsha5401.forPR
        azure-devops-token: ${{ secrets.ADO_PAT }}

